sudo: required

services:
  - docker

before_install:
  - docker build -t boilerplate_luna_api .
  - docker run -d boilerplate_luna_api
  - docker ps -a

script:
  - docker exec $(docker ps -lq) /bin/sh -c "/app/bin/boilerplate_luna_api_tests"
